server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false   # ✅ disables config server error

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/auth_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJwtAuthenticationWhichIsAtLeast32BytesLong12345}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
