server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/product_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_FILE_SIZE:5MB}

elasticsearch:
  reindex:
    on-startup: true
app:
storage:
  provider: ${IMAGE_STORAGE_PROVIDER:azure} # azure only
  azure:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    container: ${AZURE_STORAGE_CONTAINER:}
    account-name: ${AZURE_STORAGE_ACCOUNT:}
    public-base-url: ${AZURE_PUBLIC_BASE_URL:}
